In [12]:
import numpy as np
from sklearn.model_selection import train_test_split

In [17]:
#1. data
x = np.arange(1,101,1)
y = np.arange(101, 201 ,1)

print(x)

print('----------------')

print(y)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
----------------
[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154
 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172
 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190
 191 192 193 194 195 196 197 198 199 200]


<br>

### 2개의 데이터(x, y) 를 넣었을 경우

In [32]:
#1.1 dataset 분리 train_test_split - train / test (6:4)
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.6, shuffle = False)

In [33]:
x_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [34]:
y_train

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160])

In [29]:
#1.1 dataset 분리 train_test_split - train / test (6:4)
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.6, random_state = 1)

In [30]:
x_train

array([87, 54, 78, 16, 84, 42, 46, 92, 27, 99, 44, 56, 25,  5, 59, 50, 22,
       88,  4, 75, 31, 67, 71, 43, 48, 90,  9, 61,  1, 91, 58, 23, 62, 64,
        8, 97, 14, 69, 86, 15, 30, 29, 12, 19, 21, 51, 26,  7, 72, 77,  2,
       17, 65, 80,  6, 76, 10, 73, 13, 38])

In [31]:
y_train

array([187, 154, 178, 116, 184, 142, 146, 192, 127, 199, 144, 156, 125,
       105, 159, 150, 122, 188, 104, 175, 131, 167, 171, 143, 148, 190,
       109, 161, 101, 191, 158, 123, 162, 164, 108, 197, 114, 169, 186,
       115, 130, 129, 112, 119, 121, 151, 126, 107, 172, 177, 102, 117,
       165, 180, 106, 176, 110, 173, 113, 138])

<br>

### 1개의 데이터(x) 만 넣었을 경우

In [35]:
x_train, x_test = train_test_split(x, train_size = 0.6, random_state = 1)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [36]:
x_train

array([87, 54, 78, 16, 84, 42, 46, 92, 27, 99, 44, 56, 25,  5, 59, 50, 22,
       88,  4, 75, 31, 67, 71, 43, 48, 90,  9, 61,  1, 91, 58, 23, 62, 64,
        8, 97, 14, 69, 86, 15, 30, 29, 12, 19, 21, 51, 26,  7, 72, 77,  2,
       17, 65, 80,  6, 76, 10, 73, 13, 38])

In [37]:
len(x_train)

60

<br>

### train : test : validation = 6 : 2 : 2

In [39]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.6, random_state = 1)
x_test, x_val, y_test, y_val = train_test_split(x_test, y_test, test_size=0.5, random_state=1, shuffle=False)

In [41]:
len(x_train)

60

In [42]:
len(x_test)

20

In [43]:
len(x_val)

20